### ISSUE TITLE
KCT compatibilitie workaround

### ISSUE THREAD

**Issue by falcon470** [linuxgurugamer/kspcasher#4]
So its strange kct allows me to purchase a node without cash, for the mod author\updater you may want to take a look at burocrucy, for some reason with this installed the probelm goes away and every thing works as expected, have to turn off burocrcy features but once installed it fixes all problems, dont understand why, gonna try turning off all burocrcy options and setting budget to 0 but after that all problems seem to go away with kct incompatibilitie, fourms for thiss mod seem to not be loading ill post this here when able

**Comment by linuxgurugamer** [comment]
Could you please open an issue on the KSP repo?
https://github.com/linuxgurugamer/KCT/issues

FYI, the forums are having issues right now
